export const GET_USER_PROFILE_REQUEST = "GET_USER_PROFILE_REQUEST";
export const GET_USER_PROFILE_FAILURE = "GET_USER_PROFILE_FAILURE";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";

export const UPDATE_USER_PROFILE_REQUEST = "UPDATE_USER_PROFILE_REQUEST";
export const UPDATE_USER_PROFILE_FAILURE = "UPDATE_USER_PROFILE_FAILURE";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";

export const GET_USER_PROPERTIES_REQUEST = "GET_USER_PROPERTIES_REQUEST";
export const GET_USER_PROPERTIES_FAILURE = "GET_USER_PROPERTIES_FAILURE";
export const GET_USER_PROPERTIES_SUCCESS = "GET_USER_PROPERTIES_SUCCESS";

export const GET_USER_SAVED_PROPERTIES_REQUEST =
  "GET_USER_SAVED_PROPERTIES_REQUEST";
export const GET_USER_SAVED_PROPERTIES_FAILURE =
  "GET_USER_SAVED_PROPERTIES_FAILURE";
export const GET_USER_SAVED_PROPERTIES_SUCCESS =
  "GET_USER_SAVED_PROPERTIES_SUCCESS";
