export const CREATE_PROPERTY_REQUEST = "CREATE_PROPERTY_REQUEST";
export const CREATE_PROPERTY_SUCCESS = "CREATE_PROPERTY_SUCCESS";
export const CREATE_PROPERTY_FAILURE = "CREATE_PROPERTY_FAILURE";

export const UPDATE_PROPERTY_REQUEST = "UPDATE_PROPERTY_REQUEST";
export const UPDATE_PROPERTY_SUCCESS = "UPDATE_PROPERTY_SUCCESS";
export const UPDATE_PROPERTY_FAILURE = "UPDATE_PROPERTY_FAILURE";

export const DELETE_PROPERTY_REQUEST = "DELETE_PROPERTY_REQUEST";
export const DELETE_PROPERTY_SUCCESS = "DELETE_PROPERTY_SUCCESS";
export const DELETE_PROPERTY_FAILURE = "DELETE_PROPERTY_FAILURE";

export const SAVE_PROPERTY_REQUEST = "SAVE_PROPERTY_REQUEST";
export const SAVE_PROPERTY_SUCCESS = "SAVE_PROPERTY_SUCCESS";
export const SAVE_PROPERTY_FAILURE = "SAVE_PROPERTY_FAILURE";

export const GET_PROPERTY_BY_ID_REQUEST = "GET_PROPERTY_BY_ID_REQUEST";
export const GET_PROPERTY_BY_ID_SUCCESS = "GET_PROPERTY_BY_ID_SUCCESS";
export const GET_PROPERTY_BY_ID_FAILURE = "GET_PROPERTY_BY_ID_FAILURE";

export const GET_ALL_PROPERTY_REQUEST = "GET_ALL_PROPERTY_REQUEST";
export const GET_ALL_PROPERTY_SUCCESS = "GET_ALL_PROPERTY_SUCCESS";
export const GET_ALL_PROPERTY_FAILURE = "GET_ALL_PROPERTY_FAILURE";
